# siteselection_config.yml

default:
 key1: default
 pkgs:
  - tidyverse
  - googledrive
  - ggpmisc
  - sf
  - topographer
  - terra
  - viridis
 extdata:
   dem: '1sDKyVFypWFk0BbTe43PTuDv007XycZ23'
   siteindex: '1KPpaiTZSfrq0RYMJQwNdwgCU-4rWucheW5KUN_maERs'
   siteinfo21: 'EastRiver_Proposed_Sites_2021_25.csv'
   siteinfo22: 'EastRiver_Proposed_Sites_2022_10.csv'
   asp: '1C3QE-8xK2XGTE4TvGejMyu68D-QVvx85'
   aspcored: '1gxg1yOuD7qdMK5hKnk__vWobZ0zdsRz6'
   sap: 'SapSites.csv'
 dat_raw: './data/raw'
 dat_int: './data/intermediate'
 dat_pro: './data/processed'
 dat_merged: './data/intermediate/GPS_Data_Merged_2021'
 dat_stemgeo: './data/processed/Kueppers_EastRiver_Stem_Geolocations_WGS84UTM13N'
 dat_invstems: './data/processed/CleanInvLatLon'
 drivesa: "~/.ssh/eastriver-308601-65de0446573f.json"
test:
  key1: test

production:
  key1: production

